import React from "react";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import thumbnails from "@/data/thumbnails.json";
import RenderThumbnails from "@/functions/renderThumbnails";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";

export default function articulos() {
  return (
    <>
      <Head>
        <title>MYC - Artículos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <motion.div
          initial={{ opacity: 0, y: 35 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{
            duration: 0.5,
            delay: 0.75,
          }}
        >
          <RenderThumbnails data={thumbnails} />
        </motion.div>
      </main>
      <Footer />
    </>
  );
}
