import Head from "next/head";
import styles from "@/styles/modules/Home.module.css";
import LastArticle from "@/functions/lastarticle";
import { BiChevronsDown } from "react-icons/bi";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import FAQBox from "@/functions/FAQBox";
import Footer from "@/components/Footer";

type Faq = {
  question: string;
  answer: string;
  open: boolean;
};

export default function Home() {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setShow(true);
    }, 5000);

    return () => {
      clearTimeout(timeoutId);
    };
  }, []);

  const [faqs, setFaqs] = useState<Faq[]>([
    {
      question: "¿Cuál es el propósito de este sitio web?",
      answer:
        "MYC (Mate y código) se creó con la finalidad de poder almacenar mis conocimientos de forma ordenada y cómoda, y a su vez, poder compartirlo con el resto de la comunidad de desarrolladores de una manera sencilla.",
      open: false,
    },
    {
      question: "¿Qué tecnologías se usaron?",
      answer:
        "Para crear MYC (Mate y código) se utilizó el framework NextJS, junto a herramientas externas para brindar una mejor experiencia al usuario como “react-icons” o “framer-motion.",
      open: false,
    },
    {
      question: "¿Cada cuanto se sube un artículo?",
      answer:
        "En MYC (Mate y código) solo yo me encargo de escribir los artículos, y debido a que estoy estudiando tecnologías nuevas y buscando una oportunidad laboral, no poseo un tiempo libre suficiente para mantener una constancia continua con los artículos. Aún así se suele subir al menos un artículo por mes.",
      open: false,
    },
  ]);

  const toggleFAQ = (index: number) => {
    setFaqs(
      faqs.map((faq, i) => {
        if (i === index) {
          faq.open = !faq.open;
        } else {
          faq.open = false;
        }
        return faq;
      })
    );
  };

  return (
    <>
      <Head>
        <title>MYC - Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.welcome_main}>
        <div className={styles.welcome_section}>
          <div className={styles.welcome_text}>
            <h1 className={styles.welcome_title}>Mate y código</h1>
            <div className={styles.welcome_anim}>
              <p className={styles.welcome_slogan}>Un lugar donde puedes</p>
              <div className={styles.multi_content}>
                <div className={styles.multi_words}>
                  <span className={styles.wordAnim}>Aprender</span>
                  <span className={styles.wordAnim}>Descubrir</span>
                  <span className={styles.wordAnim}>Informarte</span>
                  <span className={styles.wordAnim}>Investigar</span>
                  <span className={styles.wordAnim}>Aprender</span>
                </div>
              </div>
            </div>
          </div>
          <BiChevronsDown
            className={styles.welcome_down}
            style={{ opacity: show ? 1 : 0 }}
          />
        </div>

        <section className={styles.welcome_lastart}>
          <motion.div
            initial={{ opacity: 0, marginRight: 300 }}
            whileInView={{ opacity: 1, marginRight: 0 }}
            viewport={{ once: false }}
            transition={{
              duration: 0.75,
              delay: 0.15,
            }}
          >
            <span className={styles.welcome_lastspan}>
              Mira nuestro último artículo
            </span>
          </motion.div>
          <motion.div
            initial={{ opacity: 0, marginLeft: 300 }}
            whileInView={{ opacity: 1, marginLeft: 0 }}
            viewport={{ once: false }}
            transition={{
              duration: 0.75,
              delay: 0.15,
            }}
          >
            <LastArticle />
          </motion.div>
        </section>

        <section className={styles.faq_section}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false }}
            transition={{
              duration: 0.75,
              delay: 0.25,
            }}
          >
            <span className={styles.faq_title}>Preguntas frecuentes</span>
          </motion.div>
          <div className={styles.faq_content}>
            {faqs.map((item, i) => {
              return (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: false }}
                  transition={{
                    duration: 0.75,
                    delay: 0.25,
                  }}
                >
                  <FAQBox faq={item} index={i} toggleFAQ={toggleFAQ} />
                </motion.div>
              );
            })}
          </div>
        </section>
        <Footer />
      </main>
    </>
  );
}
